// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtLd4yoECOkQCfi1M9RgDC45hQZuSJI7k',
    appId: '1:576071996494:web:24e9839d9843189db75f1f',
    messagingSenderId: '576071996494',
    projectId: 'depressiondetectionapp',
    authDomain: 'depressiondetectionapp.firebaseapp.com',
    storageBucket: 'depressiondetectionapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6dEi_yCmysfsnXwiFKowCWoJJuTQJL0',
    appId: '1:576071996494:android:c3184853af710d91b75f1f',
    messagingSenderId: '576071996494',
    projectId: 'depressiondetectionapp',
    storageBucket: 'depressiondetectionapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqTyoN3n7OnQRnL1Ug7qEMDTiMmajEVs',
    appId: '1:576071996494:ios:d8a36d3dd93ffdc0b75f1f',
    messagingSenderId: '576071996494',
    projectId: 'depressiondetectionapp',
    storageBucket: 'depressiondetectionapp.appspot.com',
    iosBundleId: 'com.example.depressionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKqTyoN3n7OnQRnL1Ug7qEMDTiMmajEVs',
    appId: '1:576071996494:ios:a6976cd327bcd43eb75f1f',
    messagingSenderId: '576071996494',
    projectId: 'depressiondetectionapp',
    storageBucket: 'depressiondetectionapp.appspot.com',
    iosBundleId: 'com.example.depressionApp.RunnerTests',
  );
}
